pbfstore:
  public: false
  formats: [pbf]
  uri: cassandra://
  params:
    keyspace: v1
    cp: [{var: cassandra-host }]
    createIfMissing: true

pbfoverzoom:
  public: false
  formats: [pbf]
  url: overzoom://
  params:
    source: {ref:pbfstore}

default:
  public: true
  formats: [png]
  maxzoom: 18
  uri: vector://
  xml:
    loader: osm-bright-style
  xmlSetParams:
    source: {ref: pbfoverzoom}
