pbfstore:
  public: false
  formats: [pbf]
  uri: cassandra://
  params:
    keyspace: v1
    cp: [{var: cassandra-host }]
    createIfMissing: true

default:
  public: true
  formats: [png]
  uri: vector://
  xml:
    loader: osm-bright-style
  xmlSetParams:
    source: {ref: pbfstore}
