swagger: '2.0'
info:
  version: 0.0.2-snapshot
  title: Elastic Tile Service
  description: Tile provider for Kibana and other Elastic Apps
  termsOfService: https://www.elastic.co/elastic-tile-service

paths:
  # Tiles handler
  /v1/{src}/{z}/{x}/{y}.{format}:
    get:
      tags:
        - kartotherian
        - maps
        - maptiles
      description: Renders an image tile for the given source, zoom, and coordinates.
      produces:
        - image/png
        - application/json
        - application/x-protobuf
      x-amples:
        - title: get a tile in the middle of the ocean, with overzoom
          request:
            params:
              src: osm-intl
              z: 11
              x: 828
              y: 655
              format: png
          response:
            status: 200
            headers:
              content-type: image/png
